### ISSUE TITLE
Missing training file for tutorial

### ISSUE THREAD

**Issue by Slugger70** [B-UMMI/chewBBACA_tutorial#1]
The file required in one of the first steps in the tutorial is missing: Streptococcus_agalactiae.trn

Could you please supply it as part of the tutorial

**Comment by jacarrico** [comment]
Sorry about that... with the pip packaging we had to remove the training files from chewie repo and forgot this part. Just uploaded it to this repo.

**Comment by mickaelsilva** [comment]
You can also find the training files at https://github.com/mickaelsilva/prodigal_training_files. I've added also as step 1 of the tutorial guide, the installation of chewBBACA which can be found [here](https://github.com/B-UMMI/chewBBACA/wiki/0.-Setting-up-chewBBACA).

**Comment by Slugger70** [comment]
Awesome! Thanks mate!
