### ISSUE TITLE
About the prodigal

### ISSUE THREAD

**Issue by huizhen2014** [B-UMMI/chewBBACA_tutorial#2]
Hi, I am new to chewBBACA.  Through my practice and I noticed in the process of CreateSchema we should input a file suffixed with .trn, and I also was not familiar with prodigal. The codes are blow:

chewBBACA.py CreateSchema -i complete_genomes/ --cpu 6 -o schema_seed --ptf Streptococcus_agalactiae.trn

So, could you mind to tell me how to use prodigal to make a training set? Thanks.

**Comment by jacarrico** [comment]
Hello Carlos
The command line for prodigal is the following: 
`prodigal -i referenceGenome.fasta -t trfName.trn -p single`

you just have to choose a reference genome for the species of interest, which we usually use a complete genome (referenceGenome.fasta) that should be the best validated one. Then you choose the output file (rfName.trn ) and that is it.

For further information please refer to : https://github.com/hyattpd/prodigal/wiki

Hope it helped!
Cheers
JAC

**Comment by huizhen2014** [comment]
Thanks.
I have found the bacterial reference genome from genbank through NCBI website, and the cds_fna sequence in the same directory, such as this link :

ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/bacteria/Acinetobacter_baumannii/latest_assembly_versions/GCA_000015425.1_ASM1542v1

So, I was wondering why we did not use the known location directly instead  predicting it with prodigal, If we grasped the CDS location for each assemble sequence.

**Comment by mickaelsilva** [comment]
We want to keep the CDS predictions the most standardized and reproducible possible. For that reason we always use prodigal over the genomes and the usage of the same prodigal training file is the best way to ensure the best prediction result concordance. 

Also, those known locations in the cds_fna file were most probably predicted using some software, either prodigal or a similar one. Results would either be the same or very similar.

**Comment by huizhen2014** [comment]
Thanks for your pretty detailed explanation.Then, for the reference genome I usually select it from NCBI. To compare it with other sources, all of them will work well according the predicting scenario. If I made any mistakes, please help me correct them. Thanks.Hui ZhenCentral LaboratoryShen Zhen Second People's HospitalSent from my Huawei Mobile-------- Original Message --------Subject: Re: [B-UMMI/chewBBACA_tutorial] About the prodigal (#2)From: Mickael To: B-UMMI/chewBBACA_tutorial CC: Carlos Hui ,Author We want to keep the CDS predictions the most standardized and reproducible possible. For that reason we always use prodigal over the genomes and the usage of the same prodigal training file is the best way to ensure the best prediction result concordance.
Also, those known locations in the cds_fna file were most probably predicted using some software, either prodigal or a similar one. Results would either be the same or very similar.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/B-UMMI/chewBBACA_tutorial","title":"B-UMMI/chewBBACA_tutorial","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/B-UMMI/chewBBACA_tutorial"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mickaelsilva in #2: We want to keep the CDS predictions the most standardized and reproducible possible. For that reason we always use prodigal over the genomes and the usage of the same prodigal training file is the best way to ensure the best prediction result concordance. \r\n\r\nAlso, those known locations in the cds_fna file were most probably predicted using some software, either prodigal or a similar one. Results would either be the same or very similar."}],"action":{"name":"View Issue","url":"https://github.com/B-UMMI/chewBBACA_tutorial/issues/2#issuecomment-439635322"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/B-UMMI/chewBBACA_tutorial/issues/2#issuecomment-439635322",
"url": "https://github.com/B-UMMI/chewBBACA_tutorial/issues/2#issuecomment-439635322",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [B-UMMI/chewBBACA_tutorial] About the prodigal (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Mickael**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mickaelsilva",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"B-UMMI/chewBBACA_tutorial\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"B-UMMI/chewBBACA_tutorial\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/B-UMMI/chewBBACA_tutorial/issues/2#issuecomment-439635322"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 412979231\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by jacarrico** [comment]
@huizhen2014 if you are using analyzing Acinetobacter we already have a training file so you can use the option `'-trf Acinetobacter_baumannii.trn` . It was made using this reference: https://www.ncbi.nlm.nih.gov/nuccore/CP000521

**Comment by huizhen2014** [comment]
Thank you!
