### ISSUE TITLE
Error in AlleleCall tutorial

### ISSUE THREAD

**Issue by Akllarena** [B-UMMI/chewBBACA_tutorial#4]
Heisann guys. 

I am doing running the chewbacca in a conda environment (tried to downloaded chewbbaca both by conda and pip), and have basically copy pasted all your commands etc. I encounter error msg when running allelcall: 

^MProcessing GCA-000007265-protein10.fasta. Start 22:19:33-22/07/2019 Locus 2 of 3130. Done 0%.some error occu$
%i format: a number is required, not NoneType
Error on line 466

It is numerous times for most loci and results in non-valid error allele assignments. I went into the schema_seed and had a look at the different loci too, they just look normal. 
what am I doing wrong?

AK

**Comment by mickaelsilva** [comment]
should be something related to software versions I guess.

prodigal and blast versions?
python version?

**Comment by Akllarena** [comment]
chewBBACA-2.0.17.1
blast+/2.6.0
prodigal/2.6.1
conda version : 4.5.11
python version : 2.7.15.final.0

I checked the dependencies and they should be ok. Do I have too old python maybe?
I can download (or rather load the module python 3.5.1 as I am working on a cluster).

**Comment by mickaelsilva** [comment]
it works with python 3, not 2, might be that the issue :)

**Comment by Akllarena** [comment]
Hei, yes, it worked after spec right python version to my conda environment! Thanks.

**Comment by vvunderkin** [comment]
i'm having the same issue. :(

chewBBACA 2.0.17.1
blast 2.5.0
prodigal 2.6.3
conda 4.7.11
python 3.7.3

**Comment by mickaelsilva** [comment]
@jeremiahyarmie have you tried with the tutorial dataset?

**Comment by vvunderkin** [comment]
yes the tutorial dataset is the one that is failing. i can try recloning the repo and trying a fresh conda env. will report back

**Comment by vvunderkin** [comment]
this is my output

'''
etc......

%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
some error occurred
%i format: a number is required, not NoneType
Error on line 466
Finished Allele Calling at : 09:53:41-28/08/2019
Wrapping up the results
##################################################
 32 genomes used for 3130loci

 used a bsr of : 0.6

18908 exact matches found out of 100160

18.87779552715655 percent of exact matches 
##################################################

Writing output files

Genome	EXC	INF	LNF	PLOT	NIPH	ALM	ASM
GCA_000007265.1_ASM726v1_genomic.fna	2442	0	688	0	0	0	0
GCA_000012705.1_ASM1270v1_genomic.fna	2349	0	780	0	1	0	0
GCA_000196055.1_ASM19605v1_genomic.fna	2299	0	789	0	42	0	0
GCA_000299135.1_ASM29913v1_genomic.fna	2254	0	876	0	0	0	0
GCA_000302475.2_ASM30247v2_genomic.fna	2058	0	1072	0	0	0	0
GCA_000427035.1_09mas018883_genomic.fna	2392	0	738	0	0	0	0
GCA_000427055.1_ILRI112_genomic.fna	2240	0	889	0	1	0	0
GCA_000427075.1_ILRI005_genomic.fna	2353	0	777	0	0	0	0
GCA_000599965.1_ASM59996v1_genomic.fna	2038	0	1091	0	1	0	0
GCA_000636115.1_ASM63611v1_genomic.fna	2035	0	1094	0	1	0	0
GCA_000689235.1_GBCO_p1_genomic.fna	2287	0	842	0	1	0	0
GCA_000730215.2_ASM73021v2_genomic.fna	2490	0	640	0	0	0	0
GCA_000730255.1_ASM73025v1_genomic.fna	2321	0	808	0	1	0	0
GCA_000782855.1_ASM78285v1_genomic.fna	2301	0	829	0	0	0	0
GCA_000831105.1_ASM83110v1_genomic.fna	2392	0	733	0	5	0	0
GCA_000831125.1_ASM83112v1_genomic.fna	2391	0	732	0	7	0	0
GCA_000831145.1_ASM83114v1_genomic.fna	2420	0	704	0	6	0	0
GCA_000967445.1_ASM96744v1_genomic.fna	2038	0	1091	0	1	0	0
GCA_001026925.1_ASM102692v1_genomic.fna	2323	0	807	0	0	0	0
GCA_001190805.1_ASM119080v1_genomic.fna	2254	0	875	0	1	0	0
GCA_001190825.1_ASM119082v1_genomic.fna	2251	0	878	0	1	0	0
GCA_001190845.1_ASM119084v1_genomic.fna	2251	0	878	0	1	0	0
GCA_001190865.1_ASM119086v1_genomic.fna	2038	0	1091	0	1	0	0
GCA_001190885.1_ASM119088v1_genomic.fna	2361	0	769	0	0	0	0
GCA_001266635.1_ASM126663v1_genomic.fna	2248	0	882	0	0	0	0
GCA_001275545.2_ASM127554v2_genomic.fna	2330	0	792	0	8	0	0
GCA_001448985.1_ASM144898v1_genomic.fna	2372	0	752	0	6	0	0
GCA_001552035.1_ASM155203v1_genomic.fna	2291	0	838	0	1	0	0
GCA_001592385.1_ASM159238v1_genomic.fna	2328	0	801	0	1	0	0
GCA_001592425.1_ASM159242v1_genomic.fna	2236	0	893	0	1	0	0
GCA_001655175.1_ASM165517v1_genomic.fna	2065	0	1065	0	0	0	0
GCA_001683515.1_ASM168351v1_genomic.fna	2329	0	800	0	1	0	0
checking the existance of paralog genes...
Detected number of paralog loci: 2780

Starting Script at : 09:38:46-28/08/2019
Finished Script at : 09:53:41-28/08/2019
'''

**Comment by mickaelsilva** [comment]
Can you try to update your blast?

**Comment by than9th** [comment]
same issue as @jeremiahyarmie  

chewBBACA 2.0.17.1
blast 2.9.0
prodigal 2.6.3
conda 4.6.14
python 3.7.3

> 
> 
> Can you try to update your blast?

**Comment by rfm-targa** [comment]
@than9th 
Please try to update `chewBBACA` to the latest version, 2.0.17.2. And tell me what's the BioPython version you have installed, please. This issue is similar to [this issue](https://github.com/B-UMMI/chewBBACA/issues/39), that was already closed in the main repository of chewBBACA.

**Comment by than9th** [comment]
> 
> 
> @than9th
> Please try to update `chewBBACA` to the latest version, 2.0.17.2. And tell me what's the BioPython version you have installed, please. This issue is similar to [this issue](https://github.com/B-UMMI/chewBBACA/issues/39), that was already closed in the main repository of chewBBACA.

Thanks. it works with the 2.0.17.2, and the biopython was updated to 1.74.
