### ISSUE TITLE
How to get the cgMLST_all.tsv

### ISSUE THREAD

**Issue by ryanjoel** [B-UMMI/chewBBACA_tutorial#5]
In the tutorial, "Now the file cgMLST_completegenomes/cgMLST.tsv can be concatenated with the allele call result from the 680 genomes results_all/results_20180202T112710/results_alleles.tsv", I don't know how to concatenate these two files to get the cgMLST_all.tsv

**Comment by pedrorvc** [comment]
Hello @ryanjoel,

The cgMLST_all.tsv can be found at https://github.com/B-UMMI/chewBBACA_tutorial/blob/master/analysis_all/cgMLST_all.tsv.

The concatenation of the files was achieved using the _JoinProfiles_ module that takes as input 2 profile files.
An example command is:
`chewBBACA.py JoinProfiles -p1 results_cg/results_(timestamp)/cgMLST_completegenomes/cgMLST.tsv -p2 results_all/results_20180202T112710/results_alleles.tsv -o cgMLST_all.tsv
`

The -p1 profile is the file obtained after running the _ExtractCgMLST_ module, change the (timestamp) to the appropriate value. The -p2 profile is the file provided with the tutorial.

If you have any questions, don't hesitate to ask!

Cheers,
Pedro

**Comment by pedrorvc** [comment]
Closing issue. We have updated the README to clarify this issue.

Feel free to reopen if you have more questions about the tutorial.
